# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
# default_install_hook_types: ["pre-commit"]
fail_fast: true
# default_language_version:
#     python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.2"
    hooks:
      - id: ruff
        name: Code linter (Ruff)
        args: [ --fix ]
      - id: ruff-format
        name: Code formatter (Ruff)

  - repo: https://github.com/pycqa/bandit
    rev: "1.7.9"
    hooks:
      - id: bandit
        name: Code security analysis (bandit)
        args: ["-c", "pyproject.toml", "-r", "app", "--severity=medium"]
        pass_filenames: false
        # stages: [push]  # Uncomment to temporarily accelerate local commits

