# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
# default_install_hook_types: ["pre-commit"]
fail_fast: true
# default_language_version:
#     python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.1"
    hooks:
      - id: ruff
        name: Code linter (Ruff)
        args: [--fix]
      - id: ruff-format
        name: Code formatter (Ruff)

  - repo: https://github.com/pycqa/bandit
    rev: "1.8.5"
    hooks:
      - id: bandit
        name: Code security analysis (bandit)
        args: ["-c", "pyproject.toml", "-r", "app", "--severity=medium"]
        pass_filenames: false
        additional_dependencies: ["bandit[toml]"]
        # stages: [push]  # Uncomment to temporarily accelerate local commits

  - repo: https://github.com/djlint/djlint
    rev: v1.36.4
    hooks:
      - id: djlint
        name: djLint
        entry: djlint --reformat
        language: python
        files: \.(html|j2)$
