[project]
name = "thebigfilmdatabase-website"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi~=0.138.2",
    "httpx~=0.28.1",
    "Jinja2~=3.1.6",
    "limits~=5.8.0",
    "pydantic~=2.13.4",
    "pydantic-settings~=2.14.2",
    "uvicorn~=0.49.0",
    "zxing-cpp==3.0.0",
]

[dependency-groups]
dev = [
    "pre-commit~=4.6.0",
    "pytest>=9.1.1",
]
install = ["numpy~=2.3.2", "pandas~=2.3.2"]

[tool.uv]
package = false

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.bandit]
targets = ["app"]
exclude_dirs = ["app/healthcheck.py"]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = [    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["E501"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends", "fastapi.Query", "fastapi.params.Query"]
